site_name: Defensive Works
site_description: Security automation & detection engineering at scale
site_url: https://docs.defensive.works
site_author: Raajhesh Kannaa Chidambaram

docs_dir: content

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.instant  Add this at a later date
    - navigation.tabs
    - navigation.indexes
  palette:
    scheme: slate
    primary: black
    accent: green
  font:
    code: JetBrains Mono

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages # non-standard
#  - minify:
#      minify_html: true
#      minify_js: true
#      minify_css: true

#extra_javascript:
#  - javascripts/matomo.min.js

#repo_name: Defensive Works 
#repo_url: https://github.com/raajheshkannaa/defensive.works
#edit_uri: edit/main/content/

extra_css:
  - assets/terminal-theme.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raajheshkannaa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/raajhesh-kannaa-chidambaram/
    - icon: fontawesome/brands/github
      link: https://github.com/raajheshkannaa
